### ISSUE TITLE
How do I run this with systemd service?

### ISSUE THREAD

**Issue by Impa10r** [LN-Zap/bitcoin-blended-fee-estimator#28] opened 2024-02-10 20:20 UTC
### Detailed Description

I tried with docker version first, but systemctl cannot stop it:
ExecStart=/usr/bin/docker run -p 3000:3000 lnzap/bitcoin-blended-fee-estimator:latest
KillMode=process

If I use bare metal version like this:
WorkingDirectory=/home/vlad/bitcoin-blended-fee-estimator
ExecStart=/home/vlad/.nvm/versions/node/v20.8.0/bin/npm start

...it won't start:
 npm[17074]: > bitcoin-blended-fee-estimator@1.0.0 start
npm[17074]: > bun run src/server.tsx
npm[17089]: sh: 1: bun: not found

**Comment by mrfelton** [comment] 2024-02-11 09:24
> bun: not found

Indicates that you don't have bun installed on your system. See [prerequisites](https://github.com/LN-Zap/bitcoin-blended-fee-estimator?tab=readme-ov-file#prerequisites). Make sure you have bun installed on your system. https://bun.sh/

**Comment by Impa10r** [comment] 2024-02-11 10:05
No, it is installed and I can run npm start from the command line. Systemd services no not know paths.

**Comment by Impa10r** [comment] 2024-02-11 10:07
And with docker run, it cannot be stopped with ctrl-c from command line, so systemctl stop also fails to stop it.

**Comment by mrfelton** [comment] 2024-02-11 10:14
> No, it is installed and I can run npm start from the command line. Systemd services do not know paths.

I think you should be using `bun start` rather than `npm start`. But if the problem is with your PATH in Systemd context, can you supply the full path to `bun` or ensure that `PATH` env var includes the location where you installed `bun` to?

**Comment by mrfelton** [comment] 2024-02-11 10:15
> And with docker run, it cannot be stopped with ctrl-c from command line, so systemctl stop also fails to stop it.

Gotcha, thanks for reporting. Will look into that.

**Comment by mrfelton** [comment] 2024-02-11 11:10
ctrl+c issue sill be fixed with https://github.com/LN-Zap/bitcoin-blended-fee-estimator/pull/29

**Comment by Impa10r** [comment] 2024-02-11 11:34
> > No, it is installed and I can run npm start from the command line. Systemd services do not know paths.
> 
> I think you should be using `bun start` rather than `npm start`. But if the problem is with your PATH in Systemd context, can you supply the full path to `bun` or ensure that `PATH` env var includes the location where you installed `bun` to?

Thanks. This can be mentioned in readme.

**Closed** 2024-02-11 11:35 UTC
Labels: type:enhancement

**Comment by M1ch43lV** [comment] 2024-02-11 20:30
Without using docker I use this kind of systemd:

```[Unit]
Description=Bitcoin Fee Server
After=network.target

[Service]
User=admin
Group=admin
WorkingDirectory=/home/admin/bitcoin-blended-fee-estimator
ExecStart=/home/admin/.bun/bin/bun run --hot src/server.tsx
Restart=on-failure
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target```

**Comment by mrfelton** [comment] 2024-02-11 20:42
You probably shouldn't be running with the `hot` flag @M1ch43lV . That'd be more for local development and would add a small amount of overhead that you don't need when running in production.`

Maybe something like `ExecStart=/home/admin/.bun/bin/bun start` would be better.

**Comment by M1ch43lV** [comment] 2024-02-11 21:22
Thanks for the proposal.
The option ```start``` returns an error.
It works with the following line omitting ```--hot```.

```ExecStart=/home/admin/.bun/bin/bun run src/server.tsx```
